import { Category, Product, Order, InventoryAdjustment, BankSettings } from './types';

export const INITIAL_BANK_SETTINGS: BankSettings = {
  upi_id: 'freshmart@okhdfcbank',
  merchant_name: 'FreshMart Local Grocery',
  account_holder: 'FreshMart Retail Private Limited',
  account_number: '50200084729102',
  ifsc_code: 'HDFC0001234',
  bank_name: 'HDFC Bank',
  branch_name: 'Indiranagar Branch, Bengaluru',
  account_type: 'Current Account',
  razorpay_key_id: 'rzp_test_freshmart123',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_produce',
    name: 'Fruits & Vegetables',
    slug: 'fruits-vegetables',
    icon: 'Apple',
    description: 'Mandi-fresh organic fruits and farm-crisp Indian vegetables',
    display_order: 1,
  },
  {
    id: 'cat_dairy',
    name: 'Dairy, Paneer & Eggs',
    slug: 'dairy-eggs',
    icon: 'Milk',
    description: 'Fresh cow milk, malai paneer, pure desi ghee, butter, and farm eggs',
    display_order: 2,
  },
  {
    id: 'cat_staples',
    name: 'Atta, Rice, Dal & Oil',
    slug: 'staples-grains',
    icon: 'Wheat',
    description: 'Sharbati wheat flour, aromatic basmati, unpolished pulses, and kachi ghani oils',
    display_order: 3,
  },
  {
    id: 'cat_snacks',
    name: 'Namkeen, Snacks & Biscuits',
    slug: 'snacks-munchies',
    icon: 'Cookie',
    description: 'Haldiram bhujia, roasted dry fruits, tea biscuits, and sweet mithai',
    display_order: 4,
  },
  {
    id: 'cat_beverages',
    name: 'Tea, Coffee & Cold Drinks',
    slug: 'beverages',
    icon: 'Coffee',
    description: 'Assam CTC tea, South Indian filter coffee, mango lassi, and fresh juices',
    display_order: 5,
  },
  {
    id: 'cat_bakery',
    name: 'Bakery, Pav & Breads',
    slug: 'bakery-bread',
    icon: 'Croissant',
    description: 'Fresh ladi pav, whole wheat brown bread, burger buns, and rusk toast',
    display_order: 6,
  },
  {
    id: 'cat_household',
    name: 'Cleaning & Household',
    slug: 'household-cleaning',
    icon: 'Sparkles',
    description: 'Dishwash bars, floor cleaners, detergent powder, and pooja essentials',
    display_order: 7,
  },
  {
    id: 'cat_personal',
    name: 'Personal Care & Hygiene',
    slug: 'personal-care',
    icon: 'Heart',
    description: 'Ayurvedic soaps, herbal shampoos, toothpaste, and skin care',
    display_order: 8,
  },
  {
    id: 'cat_frozen',
    name: 'Frozen Snacks & Peas',
    slug: 'frozen-foods',
    icon: 'Snowflake',
    description: 'Sweet green peas, veg paneer samosas, potato smiles, and ice creams',
    display_order: 9,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. Fruits & Vegetables
  {
    id: 'prod_banana',
    name: 'Fresh Robusta Bananas (Kela)',
    slug: 'fresh-robusta-bananas',
    description: 'Naturally ripened, sweet and potassium-rich South Indian robusta bananas.',
    category_id: 'cat_produce',
    price: 45,
    compare_at_price: 55,
    unit: '1 kg (approx 6-7 pcs)',
    image_url: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 45,
    reorder_level: 10,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T08:00:00Z',
  },
  {
    id: 'prod_mango',
    name: 'Ratnagiri Alphonso Mangoes (Hapus)',
    slug: 'ratnagiri-alphonso-mangoes',
    description: 'GI-tagged authentic Ratnagiri Alphonso mangoes with rich aroma and saffron sweetness.',
    category_id: 'cat_produce',
    price: 599,
    compare_at_price: 750,
    unit: '1 Dozen (12 pcs)',
    image_url: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 20,
    reorder_level: 5,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T08:15:00Z',
  },
  {
    id: 'prod_tomato',
    name: 'Farm Fresh Hybrid Red Tomatoes (Tamatar)',
    slug: 'farm-fresh-hybrid-tomatoes',
    description: 'Plump, firm, and juicy red tomatoes sourced straight from local agricultural farms.',
    category_id: 'cat_produce',
    price: 35,
    compare_at_price: 45,
    unit: '1 kg',
    image_url: 'https://images.unsplash.com/photo-1546470427-227c7369a4fb?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 50,
    reorder_level: 12,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T08:30:00Z',
  },
  {
    id: 'prod_onion',
    name: 'Nashik Red Onions (Pyaaz)',
    slug: 'nashik-red-onions',
    description: 'High-pungency, premium grade red onions from Nashik with long shelf life.',
    category_id: 'cat_produce',
    price: 38,
    compare_at_price: 48,
    unit: '1 kg',
    image_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 60,
    reorder_level: 15,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T08:45:00Z',
  },
  {
    id: 'prod_potato',
    name: 'Pahari Fresh Potatoes (Aloo)',
    slug: 'pahari-fresh-potatoes',
    description: 'Dirt-free, smooth-skinned potatoes ideal for roasting, curries, and aloo parathas.',
    category_id: 'cat_produce',
    price: 32,
    compare_at_price: 40,
    unit: '1 kg',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 75,
    reorder_level: 20,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T09:00:00Z',
  },
  {
    id: 'prod_spinach',
    name: 'Crisp Green Palak (Spinach)',
    slug: 'crisp-green-palak',
    description: 'Tender, washed and pesticide-free green spinach bunches harvested this morning.',
    category_id: 'cat_produce',
    price: 25,
    compare_at_price: 35,
    unit: '250 g bunch',
    image_url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 28,
    reorder_level: 8,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T09:15:00Z',
  },

  // 2. Dairy & Paneer
  {
    id: 'prod_paneer',
    name: 'Fresh Malai Paneer Block',
    slug: 'fresh-malai-paneer-block',
    description: 'Soft, melt-in-mouth cottage cheese made from 100% pure pasteurized cow milk.',
    category_id: 'cat_dairy',
    price: 95,
    compare_at_price: 110,
    unit: '200 g pack',
    image_url: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 30,
    reorder_level: 6,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T09:30:00Z',
  },
  {
    id: 'prod_ghee',
    name: 'Pure Desi Cow Ghee (A2 Bilona)',
    slug: 'pure-desi-cow-ghee',
    description: 'Aromatic, golden granular desi ghee made using traditional Vedic bilona churning.',
    category_id: 'cat_dairy',
    price: 395,
    compare_at_price: 450,
    unit: '500 ml jar',
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 25,
    reorder_level: 5,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T09:45:00Z',
  },
  {
    id: 'prod_milk',
    name: 'Pasteurized Full Cream Cow Milk',
    slug: 'pasteurized-full-cream-cow-milk',
    description: 'Homogenized rich whole milk packed daily under sterile cold chain storage.',
    category_id: 'cat_dairy',
    price: 66,
    compare_at_price: 70,
    unit: '1 Litre pouch',
    image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 40,
    reorder_level: 10,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod_butter',
    name: 'Salted Dairy Table Butter',
    slug: 'salted-dairy-table-butter',
    description: 'Creamy, delicious pasteurized table butter for breakfast toasts, pav bhaji, and parathas.',
    category_id: 'cat_dairy',
    price: 275,
    compare_at_price: 290,
    unit: '500 g pack',
    image_url: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 35,
    reorder_level: 8,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T10:15:00Z',
  },
  {
    id: 'prod_eggs',
    name: 'Farm Fresh White Eggs (Tray)',
    slug: 'farm-fresh-white-eggs',
    description: 'Cleaned, sanitized and protein-rich poultry farm eggs with bright yolks.',
    category_id: 'cat_dairy',
    price: 88,
    compare_at_price: 100,
    unit: '12 pcs (1 Dozen)',
    image_url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 40,
    reorder_level: 10,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T10:30:00Z',
  },

  // 3. Atta, Rice, Dal & Oil (Staples)
  {
    id: 'prod_atta',
    name: 'MP Sharbati Whole Wheat Atta',
    slug: 'mp-sharbati-whole-wheat-atta',
    description: '100% pure whole wheat grain flour with natural dietary fiber for soft, fluffy rotis.',
    category_id: 'cat_staples',
    price: 255,
    compare_at_price: 295,
    unit: '5 kg bag',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 35,
    reorder_level: 8,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T10:45:00Z',
  },
  {
    id: 'prod_basmati',
    name: 'Royal Aged Basmati Rice (Daawat / Kohinoor)',
    slug: 'royal-aged-basmati-rice',
    description: 'Extra long aged grain basmati rice with sweet natural fragrance for biryanis and pulao.',
    category_id: 'cat_staples',
    price: 165,
    compare_at_price: 199,
    unit: '1 kg pouch',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 30,
    reorder_level: 8,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T11:00:00Z',
  },
  {
    id: 'prod_toor_dal',
    name: 'Unpolished Desi Toor Dal (Arhar)',
    slug: 'unpolished-desi-toor-dal',
    description: 'Naturally grown, pesticide-free yellow toor dal with quick-cooking high protein yield.',
    category_id: 'cat_staples',
    price: 170,
    compare_at_price: 195,
    unit: '1 kg pack',
    image_url: 'https://images.unsplash.com/photo-1585994192701-f1a505c817ea?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 40,
    reorder_level: 10,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T11:15:00Z',
  },
  {
    id: 'prod_mustard_oil',
    name: 'Kachi Ghani Cold Pressed Mustard Oil',
    slug: 'kachi-ghani-mustard-oil',
    description: 'Traditional wood-pressed pungent mustard oil for authentic Indian cooking and pickling.',
    category_id: 'cat_staples',
    price: 175,
    compare_at_price: 210,
    unit: '1 Litre bottle',
    image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 25,
    reorder_level: 6,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T11:30:00Z',
  },

  // 4. Namkeen & Munchies
  {
    id: 'prod_bhujia',
    name: 'Haldiram Bikaneri Bhujia Sev',
    slug: 'haldiram-bikaneri-bhujia-sev',
    description: 'Classic spicy moth bean and gram flour crunchy snack with authentic Rajasthani taste.',
    category_id: 'cat_snacks',
    price: 115,
    compare_at_price: 130,
    unit: '400 g pack',
    image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 35,
    reorder_level: 8,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T11:45:00Z',
  },
  {
    id: 'prod_almonds',
    name: 'California Jumbo Almonds (Badam Giri)',
    slug: 'california-jumbo-almonds',
    description: 'Crispy, premium whole almonds packed with Vitamin E and brain-boosting nutrients.',
    category_id: 'cat_snacks',
    price: 340,
    compare_at_price: 420,
    unit: '500 g pouch',
    image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 20,
    reorder_level: 5,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T12:00:00Z',
  },

  // 5. Tea & Coffee
  {
    id: 'prod_chai',
    name: 'Tata Tea Gold Premium Assam & Darjeeling Chai',
    slug: 'tata-tea-gold-premium-chai',
    description: 'A rich blend of fine Assam CTC tea with gently rolled Darjeeling long leaves.',
    category_id: 'cat_beverages',
    price: 260,
    compare_at_price: 310,
    unit: '500 g pack',
    image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 30,
    reorder_level: 8,
    is_active: true,
    is_featured: true,
    created_at: '2026-08-01T12:15:00Z',
  },
  {
    id: 'prod_filter_coffee',
    name: 'South Indian Filter Coffee Powder (80:20 Chicory)',
    slug: 'south-indian-filter-coffee',
    description: 'Freshly roasted Arabica and Robusta beans ground for thick aromatic filter decoction.',
    category_id: 'cat_beverages',
    price: 180,
    compare_at_price: 220,
    unit: '250 g tin',
    image_url: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 22,
    reorder_level: 5,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T12:30:00Z',
  },

  // 6. Bakery & Pav
  {
    id: 'prod_ladi_pav',
    name: 'Soft Bakery Ladi Pav (Pack of 6)',
    slug: 'soft-bakery-ladi-pav',
    description: 'Freshly baked, pillow-soft ladi pav perfect for Mumbai vada pav, maska pav, and bhaji.',
    category_id: 'cat_bakery',
    price: 30,
    compare_at_price: 35,
    unit: '6 pcs pack',
    image_url: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
    stock_quantity: 25,
    reorder_level: 6,
    is_active: true,
    is_featured: false,
    created_at: '2026-08-01T12:45:00Z',
  },
];

export const INITIAL_INVENTORY_ADJUSTMENTS: InventoryAdjustment[] = [
  {
    id: 'adj_1',
    product_id: 'prod_banana',
    product_name: 'Fresh Robusta Bananas (Kela)',
    adjustment_type: 'restock',
    quantity_change: 50,
    previous_quantity: 0,
    new_quantity: 50,
    reason: 'Morning farm harvest delivery received',
    performed_by: 'Alex Vance (Store Manager)',
    created_at: '2026-08-01T07:00:00Z',
  },
  {
    id: 'adj_2',
    product_id: 'prod_mango',
    product_name: 'Ratnagiri Alphonso Mangoes (Hapus)',
    adjustment_type: 'restock',
    quantity_change: 25,
    previous_quantity: 0,
    new_quantity: 25,
    reason: 'Ratnagiri GI crate consignment verified',
    performed_by: 'Alex Vance (Store Manager)',
    created_at: '2026-08-01T07:15:00Z',
  },
  {
    id: 'adj_3',
    product_id: 'prod_paneer',
    product_name: 'Fresh Malai Paneer Block',
    adjustment_type: 'restock',
    quantity_change: 35,
    previous_quantity: 0,
    new_quantity: 35,
    reason: 'Cold chain dairy crate intake',
    performed_by: 'Alex Vance (Store Manager)',
    created_at: '2026-08-01T07:30:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_1',
    order_number: 'FM-88214',
    user_id: 'usr_demo_customer',
    customer_name: 'Pooja Sharma',
    phone: '+91 98201 45678',
    email: 'pooja.sharma@example.com',
    address: {
      id: 'addr_1',
      recipient_name: 'Pooja Sharma',
      phone: '+91 98201 45678',
      street: 'Flat 402, Sunshine Apartments, Linking Road',
      landmark: 'Near Bandra Police Station',
      city: 'Mumbai',
      state: 'Maharashtra',
      postal_code: '400050',
    },
    fulfillment_type: 'delivery',
    delivery_slot: 'Today (Express within 30-45 mins)',
    payment_method: 'upi_intent',
    payment_status: 'paid',
    order_status: 'confirmed',
    transaction_id: 'UPI-TXN-98421045',
    utr_number: '324598127654',
    payment_details: {
      wallet_provider: 'GOOGLE_PAY',
      upi_id: 'pooja@okhdfcbank',
    },
    subtotal: 694,
    delivery_fee: 0,
    tax: 35,
    total: 729,
    notes: 'Please call before ringing the doorbell',
    created_at: '2026-08-20T10:30:00Z',
    items: [
      {
        id: 'item_1',
        order_id: 'ord_1',
        product_id: 'prod_mango',
        product_name: 'Ratnagiri Alphonso Mangoes (Hapus)',
        unit: '1 Dozen (12 pcs)',
        unit_price: 599,
        quantity: 1,
        subtotal: 599,
        image_url: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80',
      },
      {
        id: 'item_2',
        order_id: 'ord_1',
        product_id: 'prod_paneer',
        product_name: 'Fresh Malai Paneer Block',
        unit: '200 g pack',
        unit_price: 95,
        quantity: 1,
        subtotal: 95,
        image_url: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=600&auto=format&fit=crop&q=80',
      },
    ],
  },
];
